var zh = {
    Save: "儲存",
    "Save all": "全部儲存",
    Rename: "重新命名",
    Open: "開啟",
    Edit: "編輯",
    Delete: "刪除",
    Folder: "資料夾",
    "Add New": "新建",
    Size: "尺寸",
    Date: "日期",
    "back to parent folder": "返回主資料夾",
    Download: "下載",
    Type: "類型",
    Information: "資訊",
    Files: "檔案",
    Table: "表格",
    Cards: "卡片",
    Total: "總和",
    "Are you sure ?": "您確定嗎 ?",
    Details: "細節",
    "Enter a new name": "輸入新名稱",
    Add: "增加",
    "Select something": "選取",
    "Download file": "下載檔案",
    Preview: "預覽",
    Refresh: "重新整理",
    "Are you sure you want to exit without saving?": "您確定要離開而不存檔?",
    "Save before closing?": "關閉前存檔?",
    Copy: "複製",
    Cut: "剪下",
    Paste: "貼上",
    "Deleting...": "刪除中...",
    "Copying...": "複製中...",
    "Moving...": "移動中...",
    Folders: "資料夾",
    "Search results": "搜尋結果",
    "Search results in": "搜尋結果於",
    "Search files and folders": "搜尋檔案與資料夾",
    "Add new file": "新增檔案",
    "Add new folder": "新增資料夾",
    "Upload file": "上傳檔案",
    folder: "資料夾",
    file: "檔案",
    archive: "封存檔",
    audio: "音檔",
    image: "圖檔",
    video: "影片檔",
    code: "編碼檔",
    document: "文件",
    of: "於",
    used: "已使用",
    "Open item location": "開啟項目位置",
    "Are you sure you want to delete": "您確定要刪除?",
    "these items:": "這些項目:",
    "this item:": "此項目:",
    "Delete files": "刪除檔案",
    and: "和",
    "more file(s)": "更多檔案",
    "Close the editor": "關閉編輯",
    "Close this file": "關閉此檔案",
    "Owner": "所有者",
    "Permissions": "權限",
    "Change Permissions": "更改權限",
    "Set": "設定",
    "Extract": "解壓縮",
    "Extract directory": "解壓縮到資料夾",
    "Extracting...": "解壓縮中...",
    "Compress": "壓縮",
    "Compressing...": "壓縮中...",
};
