var uk = {
    Save: "Зберегти",
    "Save all": "Зберегти все",
    Rename: "Перейменувати",
    Open: "Відкрити",
    Edit: "Редагувати",
    Delete: "Видалити",
    Folder: "Папка",
    "Add New": "Додати",
    Size: "Розмір",
    Date: "Дата",
    "back to parent folder": "назад до батьківської папки",
    Download: "Скачати",
    Type: "Тип",
    Information: "Інформація",
    Files: "Файли",
    Table: "Таблиця",
    Cards: "Картки",
    Total: "Разом",
    "Are you sure ?": "Ви впевнені ?",
    Details: "Подробиці",
    "Enter a new name": "Введіть нове ім'я",
    Add: "Додати",
    "Select something": "Виберіть щось",
    "Download file": "Завантажити файл",
    Preview: "Перегляд",
    Refresh: "Оновити",
    "Are you sure you want to exit without saving?": "Ви дійсно бажаєте вийти без збереження?",
    "Save before closing?": "Зберегти перед закриттям?",
    Copy: "Копіювати",
    Cut: "Вирізати",
    Paste: "Вставити",
    "Deleting...": "Видалення...",
    "Copying...": "Копіювання...",
    "Moving...": "Переміщення ...",
    Folders: "Папки",
    "Search results": "Результати пошуку",
    "Search results in": "Результати пошуку в",
    "Search files and folders": "Пошук файлів та папок",
    "Add new file": "Новий файл",
    "Add new folder": "Нова папка",
    "Upload file": "Завантажити файл",
    folder: "папка",
    file: "файл",
    archive: "архів",
    audio: "аудіо",
    image: "зображення",
    video: "відео",
    code: "код",
    document: "документ",
    of: "з",
    used: "використовується",
    "Open item location": "Відкрити розташування елемента",
    "Are you sure you want to delete": "Ви впевнені, що бажаєте видалити",
    "these items:": "ці пункти:",
    "this item:": "цей пункт:",
    "Delete files": "Видалити файли",
    and: "та",
    "more file(s)": "більше файлів",
    "Close the editor": "Закрити редактор",
    "Close this file": "Закрити цей файл",
    "Owner": "Власник",
    "Permissions": "Права доступу",
    "Change Permissions": "Змінити права доступу",
    "Set": "Встановити",
    "Extract": "Розпакувати",
    "Extract directory": "Розпакувати каталог",
    "Extracting...": "Розпакування...",
    "Compress": "Стиснути",
    "Compressing...": "Стиснення...",
};