var sk = {
  Save: "Uložiť",
  "Save all": "Uložiť všetko",
  Rename: "Premenovať",
  Open: "Otvoriť",
  Edit: "Upraviť",
  Delete: "Zmazať",
  Folder: "Priečinok",
  "Add New": "Pridať nový",
  Size: "Veľkosť",
  Date: "Dátum",
  "back to parent folder": "Späť do nadradeného priečinku",
  Download: "Stiahnuť",
  Type: "Typ",
  Information: "Informácie",
  Files: "Súbory",
  Table: "Tabuľka",
  Cards: "Karty",
  Total: "Celkom",
  "Are you sure ?": "Ste si istí?",
  Details: "Podrobnosti",
  "Enter a new name": "Zadajte nový názov",
  Add: "Pridať",
  "Select something": "Najskôr vyberte",
  "Download file": "Stiahnuť súbor",
  Preview: "Náhľad",
  Refresh: "Obnoviť",
  "Are you sure you want to exit without saving?": "Ste si istí, že chcete odísť bez uloženia?",
  "Save before closing?": "Uložiť pred zatvorením?",
  Copy: "Kopírovať",
  Cut: "Vystrihnúť",
  Paste: "Prilepiť",
  "Deleting...": "Maže sa ...",
  "Copying...": "Kopíruje sa ...",
  "Moving...": "Presúva sa ...",
  Folders: "Priečinky",
  "Search results": "Výsledky hľadania",
  "Search results in": "Výsledky hľadania pre",
  "Search files and folders": "Hľadať súbory a priečinky",
  "Add new file": "Pridať nový súbor",
  "Add new folder": "Pridať nový priečinok",
  "Upload file": "Nahrať súbor",
  folder: "priečinok",
  file: "soubor",
  archive: "archív",
  audio: "zvuk",
  image: "obrázok",
  video: "video",
  code: "kód",
  document: "dokument",
  of: "z",
  used: "použité",
  "Open item location": "Otvoriť umiestnenie položky",
  "Are you sure you want to delete": "Ste si istí, že chcete zmazať",
  "these items:": "tieto položky:",
  "this item:": "túto položku:",
  "Delete files": "Zmazať súbory",
  and: "a",
  "more file(s)": "ďalšie súbory",
  "Close the editor": "Zavrieť editor",
  "Close this file": "Zavrieť tento súbor",
  "Owner": "Vlastník",
  "Permissions": "Práva",
  "Change Permissions": "Zmeniť práva",
  "Set": "Nastaviť",
  "Extract": "Rozbaliť",
  "Extract directory": "Rozbaliť priečinok",
  "Extracting...": "Prebieha rozbaľovanie ...",
  "Compress": "Komprimovať",
  "Compressing...": "Prebieha komprimácia ..."
};
