var en = {
    Save: "حفظ",
    "Save all": "حفظ الكل",
    Rename: "اعادة تسمية",
    Open: "فتح",
    Edit: "تعديل",
    Delete: "حذف",
    Folder: "المجلد",
    "Add New": "اضف جديد",
    Size: "الحجم",
    Date: "التاريخ",
    "back to parent folder": "عودة للجذر",
    Download: "تحميل",
    Type: "النوع",
    Information: "معلومات",
    Files: "ملفات",
    Table: "جدول",
    Cards: "البطاقات",
    Total: "المجموع",
    "Are you sure ?": "هل انت متأكد؟",
    Details: "التفاصيل",
    "Enter a new name": "اضف اسم جديد",
    Add: "اضف",
    "Select something": "اختر شيئاً",
    "Download file": "تحميل الملف",
    Preview: "عرض",
    Refresh: "تحديث",
    "Are you sure you want to exit without saving?": "الخروج بدون حفظ التغييرات؟",
    "Save before closing?": "الحفظ قبل الإغلاق؟",
    Copy: "نسخ",
    Cut: "قص",
    Paste: "لصق",
    "Deleting...": "جار الحذف...",
    "Copying...": "جار النسخ...",
    "Moving...": "جار النقل...",
    Folders: "المجلدات",
    "Search results": "نتائج البحث",
    "Search results in": "نتائج البحث عن",
    "Search files and folders": "ابحث عن الملفات والمجلدات",
    "Add new file": "اضف ملف جديد",
    "Add new folder": "اضف مجلد جديد",
    "Upload file": "رفع ملف",
    folder: "مجلد",
    file: "ملف",
    archive: "نسخة مضغوطة",
    audio: "ملف صوتي",
    image: "صورة",
    video: "فيديو",
    code: "شفرة",
    document: "وثيقة",
    of: "من",
    used: "مُستخدم",
    "Open item location": "فتح موقع الحفظ",
    "Are you sure you want to delete": "هل أنت متأكد أنك تريد حذف",
    "these items:": "هذه العناصر:",
    "this item:": "هذا العنصر:",
    "Delete files": "حذف الملفات",
    and: "و",
    "more file(s)": "ملف/ات اكثر",
    "Close the editor": "إغلاق المحرر",
    "Close this file": "اغلق هذا الملف",
    "Owner": "المالك",
    "Permissions": "التصاريح",
    "Change Permissions": "تغيير التصاريخ",
    "Set": "تعيين",
    "Extract": "إستخراج",
    "Extract directory": "استخراج الدليل",
    "Extracting...": "جار الاستخراج...",
    "Compress": "ضغط",
    "Compressing...": "جاري الضغط...",
};