var lt = {
    Save: "Išsaugoti",
    "Save all": "Išsaugoti viska",
    Rename: "Pervadinti",
    Open: "Atidaryti",
    Edit: "Redaguoti",
    Delete: "Ištrinti",
    Folder: "Aplankas",
    "Add New": "Pridėti naują",
    Size: "Dydis",
    Date: "Data",
    "back to parent folder": "atgal į pirminį aplanką",
    Download: "Parsisiųsti",
    Type: "Tipas",
    Information: "Informacija",
    Files: "Failai",
    Table: "Lentelė",
    Cards: "Kortelės",
    Total: "Viso",
    "Are you sure ?": "Ar tu tuo tikras ?",
    Details: "Detalės",
    "Enter a new name": "Įveskite naują pavadinimą",
    Add: "Pridėti",
    "Select something": "Pasirinkite ką nors",
    "Download file": "Atsisiųsti failą",
    Preview: "Peržiūra",
    Refresh: "Atnaujinti",
    "Are you sure you want to exit without saving?": "Ar tikrai norite išeiti neišsaugoję?",
    "Save before closing?": "Išsaugoti prieš uždarant?",
    Copy: "Kopijuoti",
    Cut: "Iškirpti",
    Paste: "Įklijuoti",
    "Deleting...": "Ištrinama...",
    "Copying...": "Kopijuojama...",
    "Moving...": "Perkeliama...",
    Folders: "Aplankai",
    "Search results": "Paieškos rezultatai",
    "Search results in": "Paieškos rezultatai",
    "Search files and folders": "Ieškokite failų ir aplankų",
    "Add new file": "Sukurti naują failą",
    "Add new folder": "Sukurti naują aplanką",
    "Upload file": "Įkelti failą",
    folder: "aplankas",
    file: "failas",
    archive: "archyvas",
    audio: "garso įrašas",
    image: "nuotrauka",
    video: "vaizdo įrašas",
    code: "kodas",
    document: "dokumentas",
    of: "iš",
    used: "naudota",
    "Open item location": "Atidaryti elemento vietą",
    "Are you sure you want to delete": "Ar esate įsitikinę, kad norite ištrinti",
    "these items:": "šie elementai:",
    "this item:": "šis elementas:",
    "Delete files": "Ištrinti failus",
    and: "ir",
    "more file(s)": "daugiau failų",
    "Close the editor": "Uždarykite redaktorių",
    "Close this file": "Uždarykite šį failą",
    "Owner": "Savininkas",
    "Permissions": "Leidimai",
    "Change Permissions": "Keisti leidimus",
    "Set": "Nustatyti",
    "Extract": "Išskleisti",
    "Extract directory": "Išskleisti katalogą",
    "Extracting...": "Išskleidžiama...",
    "Compress": "Suspausti",
    "Compressing...": "Spaudžiama...",
};
