var hans = {
    Save: "保存",
    "Save all": "全部保存",
    Rename: "重命名",
    Open: "打开",
    Edit: "编辑",
    Delete: "删除",
    Folder: "文件夹",
    "Add New": "新建",
    Size: "规格",
    Date: "日期",
    "back to parent folder": "返回主文件夹",
    Download: "下载",
    Type: "类型",
    Information: "信息",
    Files: "文件",
    Table: "表格",
    Cards: "卡片",
    Total: "总额",
    "Are you sure ?": "您确定吗 ?",
    Details: "细节",
    "Enter a new name": "输入新名称",
    Add: "添加",
    "Select something": "选取",
    "Download file": "下载文件",
    Preview: "预览",
    Refresh: "刷新",
    "Are you sure you want to exit without saving?": "您确定要未保存就退出吗？",
    "Save before closing?": "关闭前保存？",
    Copy: "复制",
    Cut: "剪切",
    Paste: "粘贴",
    "Deleting...": "删除中...",
    "Copying...": "复制中...",
    "Moving...": "移动中...",
    Folders: "文件夹",
    "Search results": "搜索结果",
    "Search results in": "搜索结果于",
    "Search files and folders": "搜索文件和文件夹",
    "Add new file": "新增文件",
    "Add new folder": "新增文件夹",
    "Upload file": "上传文件",
    folder: "文件夹",
    file: "文件",
    archive: "归档",
    audio: "音频",
    image: "图片",
    video: "视频",
    code: "代码",
    document: "文档",
    of: "于",
    used: "已使用",
    "Open item location": "打开项目位置",
    "Are you sure you want to delete": "您确定你要删除",
    "these items:": "这些项目:",
    "this item:": "此项目:",
    "Delete files": "删除文件",
    and: "和",
    "more file(s)": "更多文件",
    "Close the editor": "关闭编辑器",
    "Close this file": "关闭此文件",
    Owner: "所有者",
    Permissions: "权限",
    "Change Permissions": "更改权限",
    Set: "设定",
    Extract: "解压",
    "Extract directory": "解压文件夹",
    "Extracting...": "解压中...",
    Compress: "压缩",
    "Compressing...": "压缩中...",
};
