var bg = {
    Save: "Запази",
    "Save all": "Запази всичко",
    Rename: "Преименуване",
    Open: "Отвори",
    Edit: "Редактиране",
    Delete: "Изтриване",
    Folder: "Папка",
    "Add New": "Нобави нов",
    Size: "Размер",
    Date: "Дата",
    "back to parent folder": "назад до главната папка",
    Download: "Свали",
    Type: "Тип",
    Information: "Информация",
    Files: "Файлове",
    Table: "Таблица",
    Cards: "Карти",
    Total: "Общо",
    "Are you sure ?": "Сигурно ли сте?",
    Details: "Детайли",
    "Enter a new name": "Въведете ново име",
    Add: "Добави",
    "Select something": "Изберете нещо",
    "Download file": "Свалете файла",
    Preview: "Преглед",
    Refresh: "Опресни",
    "Are you sure you want to exit without saving?": "Наистина ли искате да излезете без да запазите промените?",
    "Save before closing?": "Запази преди да излезеш?",
    Copy: "Копирай",
    Cut: "Изрежи",
    Paste: "Постави",
    "Deleting...": "Изтриване...",
    "Copying...": "Copying...",
    "Moving...": "Moving...",
    Folders: "Folders",
    "Search results": "Search results",
    "Search results in": "Search results in",
    "Search files and folders": "Search files and folders",
    "Add new file": "Add new file",
    "Add new folder": "Add new folder",
    "Upload file": "Upload file",
    folder: "folder",
    file: "file",
    archive: "archive",
    audio: "audio",
    image: "image",
    video: "video",
    code: "code",
    document: "document",
    of: "of",
    used: "used",
    "Open item location": "Open item location",
    "Are you sure you want to delete": "Are you sure you want to delete",
    "these items:": "these items:",
    "this item:": "this item:",
    "Delete files": "Delete files",
    and: "and",
    "more file(s)": "more file(s)",
    "Close the editor": "Close the editor",
    "Close this file": "Close this file",
    "Owner": "Owner",
    "Permissions": "Permissions",
    "Change Permissions": "Change Permissions",
    "Set": "Set",
    "Extract": "Extract",
    "Extract directory": "Extract directory",
    "Extracting...": "Extracting...",
    "Compress": "Compress",
    "Compressing...": "Compressing...",
};
