var bg = {
    Save: "Запази",
    "Save all": "Запази всичко",
    Rename: "Преименуване",
    Open: "Отвори",
    Edit: "Редактиране",
    Delete: "Изтриване",
    Folder: "Папка",
    "Add New": "Добави нов",
    Size: "Размер",
    Date: "Дата",
    "back to parent folder": "назад до главната папка",
    Download: "Свали",
    Type: "Тип",
    Information: "Информация",
    Files: "Файлове",
    Table: "Таблица",
    Cards: "Карти",
    Total: "Общо",
    "Are you sure ?": "Сигурни ли сте?",
    Details: "Детайли",
    "Enter a new name": "Въведете ново име",
    Add: "Добави",
    "Select something": "Изберете нещо",
    "Download file": "Свалете файла",
    Preview: "Преглед",
    Refresh: "Опресни",
    "Are you sure you want to exit without saving?": "Наистина ли искате да излезете без да запазите промените?",
    "Save before closing?": "Запази преди да излезеш?",
    Copy: "Копирай",
    Cut: "Изрежи",
    Paste: "Постави",
    "Deleting...": "Изтриване...",
    "Copying...": "Копиране...",
    "Moving...": "Преместване...",
    Folders: "Папки",
    "Search results": "Резултати от търсенето",
    "Search results in": "Резултати от търсенето в",
    "Search files and folders": "Търсене на файлове и папки",
    "Add new file": "Добавяне на нов файл",
    "Add new folder": "Добавяне на нова папка",
    "Upload file": "Качване на файл",
    folder: "папка",
    file: "файл",
    archive: "архив",
    audio: "аудио",
    image: "изображение",
    video: "видео",
    code: "код",
    document: "документ",
    of: "от",
    used: "използван(и)",
    "Open item location": "Отваряне на пътя на обекта",
    "Are you sure you want to delete": "Наистина ли искате да изтриете",
    "these items:": "тези обекти:",
    "this item:": "този обект:",
    "Delete files": "Изтриване на файлове",
    and: "и",
    "more file(s)": "още файл(ове)",
   "Close the editor": "Затвори редактора",
    "Close this file": "Затвори този файл",
    "Owner": "Собственик",
    "Permissions": "Права",
    "Change Permissions": "Промени правата",
    "Set": "Задай",
    "Extract": "Разархивирай",
    "Extract directory": "Разархивирай директория",
    "Extracting...": "Разархивиране...",
    "Compress": "Архивирай",
};
