var de = {
    Save: "Speichern",
    "Save all": "Alle Speichern",
    Rename: "Umbenennen",
    Open: "Öffnen",
    Edit: "Editieren",
    Delete: "Löschen",
    Folder: "Ordner",
    "Add New": "Neu hinzufügen",
    Size: "Größe",
    Date: "Datum",
    "back to parent folder": "zurück zum übergeordneten Ordner",
    Download: "Download",
    Type: "Typ",
    Information: "Information",
    Files: "Dateien",
    Table: "Tabelle",
    Cards: "Karten",
    Total: "Total",
    "Are you sure ?": "Bist du dir sicher?",
    Details: "Details",
    "Enter a new name": "Gebe einen neuen Namen ein",
    Add: "Hinzufügen",
    "Select something": "Wähle etwas aus",
    "Download file": "Datei herunterladen",
    Preview: "Vorschau",
    Refresh: "Aktualisieren",
    "Are you sure you want to exit without saving?": "Bist du dir sicher, dass du nicht speichern möchtest?",
    "Save before closing?": "Speichern vor dem schließen?",
    Copy: "Kopieren",
    Cut: "Ausschneiden",
    Paste: "Einfügen",
    "Deleting...": "Löschen...",
    "Copying...": "Kopieren...",
    "Moving...": "Verschieben...",
    Folders: "Ordner",
    "Search results": "Suchergebnisse",
    "Search results in": "Suchergebnisse in",
    "Search files and folders": "Durchsuche Dateien und Ordner",
    "Add new file": "Neue Datei hinzufügen",
    "Add new folder": "Neuen Ordner hinzufügen",
    "Upload file": "Datei hochladen",
    folder: "Ordner",
    file: "Datei",
    archive: "archive",
    audio: "audio",
    image: "image",
    video: "video",
    code: "code",
    document: "document",
    of: "of",
    used: "benutzt",
    "Open item location": "Datei öffnen",
    "Are you sure you want to delete": "Bist du dir sicher, dass du löschen möchtest?",
    "these items:": "Diese Dateien:",
    "this item:": "Diese Datei:",
    "Delete files": "Dateien löschen",
    and: "und",
    "more file(s)": "mehr Datei(en)",
    "Close the editor": "Editor schließen",
    "Close this file": "Datei schließen",
    "Owner": "Besitzer",
    "Permissions": "Rechte",
    "Change Permissions": "Rechte ändern",
    "Set": "Setzen",
    "Extract": "Entpacken",
    "Extract directory": "Verzeichnis extrahieren",
    "Extracting...": "Extrahieren...",
    "Compress": "Komprimieren",
    "Compressing...": "Komprimieren...",
};