var fa = {
    Save: "ذخیره",
    "Save all": "ذخیره همه",
    Rename: "تغییر نام",
    Open: "باز کردن",
    Edit: "ویرایش",
    Delete: "حذف",
    Folder: "پوشه",
    "Add New": "افزودن",
    Size: "اندازه",
    Date: "تاریخ",
    "back to parent folder": "بازگشت به پوشه مادر",
    Download: "دانلود",
    Type: "نوع",
    Information: "اطلاعات",
    Files: "فایل‌ها",
    Table: "جدول",
    Cards: "کارتی",
    Total: "مجموع",
    "Are you sure ?": "مطمئن هستید؟",
    Details: "جزئیات",
    "Enter a new name": "نام جدید را وارد کنید",
    Add: "افزودن",
    "Select something": "انتخاب کنید",
    "Download file": "دانلود فایل",
    Preview: "پیش نمایش",
    Refresh: "تازه‌سازی",
    "Are you sure you want to exit without saving?": "آیا مطمئن هستید که بدون ذخیره تغییرات می‌خواهید خارج شوید؟",
    "Save before closing?": "قبل از خارج شدن ذخیره شود؟",
    Copy: "کپی",
    Cut: "برش",
    Paste: "چسباندن",
    "Deleting...": "در حال حذف...",
    "Copying...": "در حال کپی...",
    "Moving...": "در حال انتقال...",
    Folders: "پوشه‌ها",
    "Search results": "نتایج جستجو",
    "Search results in": "نتایج جستجو در",
    "Search files and folders": "جستجوی فایل‌ها و پوشه‌ها",
    "Add new file": "افزودن فایل جدید",
    "Add new folder": "افزودن پوشه جدید",
    "Upload file": "آپلود فایل",
    folder: "پوشه",
    file: "فایل",
    archive: "آرشیو",
    audio: "صدا",
    image: "تصویر",
    video: "ویدئو",
    code: "کُد",
    document: "سند",
    of: "از",
    used: "استفاده شده",
    "Open item location": "بازکردن محل فایل",
    "Are you sure you want to delete": "آیا مطمئن هستید که می‌خواهید حذف کنید",
    "these items:": "این آیتم‌ها:",
    "this item:": "این آیتم:",
    "Delete files": "حذف فایل‌ها",
    and: "و",
    "more file(s)": "فایل‌های بیشتر",
    "Close the editor": "بستن ویرایشگر",
    "Close this file": "بستن این فایل",
    "Owner": "مالک",
    "Permissions": "مجوزها",
    "Change Permissions": "تغییر مجوزها",
    "Set": "تنظیم",
    "Extract": "استخراج",
    "Extract directory": "پوشه استخراج",
    "Extracting...": "در حال استخراج...",
    "Compress": "فشرده‌سازی",
    "Compressing...": "در حال فشرده‌سازی...",
};