var vi = {
    Save: "Lưu",
    "Save all": "Lưu tất cả",
    Rename: "Đổi tên",
    Open: "Mở",
    Edit: "Chỉnh sửa",
    Delete: "Xóa",
    Folder: "Thư mục",
    "Add New": "Thêm mới",
    Size: "Kích thước",
    Date: "Ngày",
    "back to parent folder": "quay về thư mục cha",
    Download: "Tải về",
    Type: "Loại",
    Information: "Thông tin",
    Files: "Tập tin",
    Table: "Bảng",
    Cards: "Thẻ",
    Total: "Tổng",
    "Are you sure ?": "Bạn có đồng ý không ?",
    Details: "Chi tiết",
    "Enter a new name": "Nhập một tên mới",
    Add: "Thêm",
    "Select something": "Chọn...",
    "Download file": "Tải tập tin",
    Preview: "Xem trước",
    Refresh: "Làm tươi",
    "Are you sure you want to exit without saving?": "Bạn có muốn thoát mà không lưu lại?",
    "Save before closing?": "Hãy lưu lại trước khi đóng?",
    Copy: "Sao chép",
    Cut: "Cắt",
    Paste: "Dán",
    "Deleting...": "Đang xóa...",
    "Copying...": "Đang sao chép...",
    "Moving...": "Đang di chuyển...",
    Folders: "Thư mục",
    "Search results": "Kết quả tìm kiếm",
    "Search results in": "Kết quả tìm kiếm trong",
    "Search files and folders": "Tìm kiếm tập tin và thư mục",
    "Add new file": "Thêm tập tin mới",
    "Add new folder": "Thêm thư mục mới",
    "Upload file": "Tải lên tập tin",
    folder: "thư mục",
    file: "tập tin",
    archive: "lưu trữ",
    audio: "âm thanh",
    image: "hình ảnh",
    video: "phim",
    code: "mã",
    document: "văn bản",
    of: "của",
    used: "đã dùng",
    "Open item location": "Mở vị trí mục",
    "Are you sure you want to delete": "Bạn có chắc chắn xóa không",
    "these items:": "những mục này:",
    "this item:": "mục này:",
    "Delete files": "Xóa tập tin",
    and: "và",
    "more file(s)": "nhiều tập tin",
    "Close the editor": "Đóng trình chỉnh sửa",
    "Close this file": "Đóng tập tin này",
    "Owner": "Người sở hữu",
    "Permissions": "Quyền",
    "Change Permissions": "Đổi quyền",
    "Set": "Gán",
    "Extract": "Giải nén",
    "Extract directory": "Giải nén thư mục",
    "Extracting...": "Đang giải nén...",
    "Compress": "Nén",
    "Compressing...": "Đang nén...",
};