var vi = {
    Save: "Lưu",
    "Save all": "Lưu tất cả",
    Rename: "Đổi tên",
    Open: "Mở",
    Edit: "Sửa",
    Delete: "Xóa",
    Folder: "Thư mục",
    "Add New": "Thêm mới",
    Size: "Kích thước",
    Date: "Ngày",
    "back to parent folder": "quay lại thư mục cha",
    Download: "Tải xuống",
    Type: "Loại",
    Information: "Thông tin",
    Files: "Tệp",
    Table: "Bảng",
    Cards: "Thẻ",
    Total: "Tổng",
    "Are you sure ?": "Bạn có chắc chắn không?",
    Details: "Chi tiết",
    "Enter a new name": "Nhập tên mới",
    Add: "Thêm",
    "Select something": "Chọn một mục",
    "Download file": "Tải tệp xuống",
    Preview: "Xem trước",
    Refresh: "Làm mới",
    "Are you sure you want to exit without saving?": "Bạn có chắc chắn muốn thoát mà không lưu?",
    "Save before closing?": "Lưu trước khi đóng?",
    Copy: "Sao chép",
    Cut: "Cắt",
    Paste: "Dán",
    "Deleting...": "Đang xóa...",
    "Copying...": "Đang sao chép...",
    "Moving...": "Đang di chuyển...",
    Folders: "Thư mục",
    "Search results": "Kết quả tìm kiếm",
    "Search results in": "Kết quả tìm kiếm trong",
    "Search files and folders": "Tìm kiếm tệp và thư mục",
    "Add new file": "Thêm tệp mới",
    "Add new folder": "Thêm thư mục mới",
    "Upload file": "Tải tệp lên",
    folder: "thư mục",
    file: "tệp",
    archive: "tệp nén",
    audio: "âm thanh",
    image: "hình ảnh",
    video: "video",
    code: "mã",
    document: "tài liệu",
    of: "của",
    used: "đã dùng",
    "Open item location": "Mở vị trí mục",
    "Are you sure you want to delete": "Bạn có chắc chắn muốn xóa",
    "these items:": "các mục này:",
    "this item:": "mục này:",
    "Delete files": "Xóa tệp",
    and: "và",
    "more file(s)": "nhiều tệp hơn",
    "Close the editor": "Đóng trình soạn thảo",
    "Close this file": "Đóng tệp này",
    "Owner": "Người sở hữu",
    "Permissions": "Quyền",
    "Change Permissions": "Thay đổi quyền",
    "Set": "Đặt",
    "Extract": "Giải nén",
    "Extract directory": "Thư mục giải nén",
    "Extracting...": "Đang giải nén...",
    "Compress": "Nén",
    "Compressing...": "Đang nén...",
};
