var ja = {
    Save: "保存",
    "Save all": "すべて保存",
    Rename: "名前を変更",
    Open: "開く",
    Edit: "編集",
    Delete: "削除",
    Folder: "フォルダー",
    "Add New": "新規",
    Size: "サイズ",
    Date: "日付",
    "back to parent folder": "親フォルダーへ戻る",
    Download: "ダウンロード",
    Type: "タイプ",
    Information: "情報",
    Files: "ファイル",
    Table: "テーブル",
    Cards: "カード",
    Total: "すべて",
    "Are you sure ?": "大丈夫ですか？",
    Details: "詳細",
    "Enter a new name": "新しい名前を入力",
    Add: "追加",
    "Select something": "選択する",
    "Download file": "ダウンロードファイル",
    Preview: "プレビュー",
    Refresh: "更新",
    "Are you sure you want to exit without saving?": "保存せずに終了しますか？",
    "Save before closing?": "閉じる前に保存しますか？",
    Copy: "コピー",
    Cut: "切り取り",
    Paste: "貼り付け",
    "Deleting...": "削除中...",
    "Copying...": "コピー中...",
    "Moving...": "移動中...",
    Folders: "フォルダー",
    "Search results": "検索結果",
    "Search results in": "での検索結果",
    "Search files and folders": "ファイルやフォルダの検索",
    "Add new file": "新しいファイルを追加",
    "Add new folder": "新しいフォルダを追加",
    "Upload file": "ファイルをアップデート",
    folder: "フォルダー",
    file: "ファイル",
    archive: "アーカイブ",
    audio: "音楽",
    image: "画像",
    video: "動画",
    code: "コード",
    document: "ドキュメント",
    of: "の",
    used: "使用",
    "Open item location": "現在のディレクトリ",
    "Are you sure you want to delete": "本当に削除しますか？",
    "these items:": "これらの項目:",
    "this item:": "このアイテム:",
    "Delete files": "削除されたファイル",
    and: "and",
    "more file(s)": "さらに表示",
    "Close the editor": "エディターを閉じる",
    "Close this file": "ファイルを閉じる",
    "Owner": "所有者",
    "Permissions": "権限",
    "Change Permissions": "権限を変更",
    "Set": "設定",
    "Extract": "展開",
    "Extract directory": "ディレクトリを展開",
    "Extracting...": "展開中...",
    "Compress": "圧縮",
    "Compressing...": "圧縮中...",
};