var en = {
    Save: "সংরক্ষণ করুন",
    "Save all": "সব সংরক্ষণ করুন",
    Rename: "নাম পরিবর্তন করুন",
    Open: "খুলুন",
    Edit: "সম্পাদনা করুন",
    Delete: "মুছে ফেলুন",
    Folder: "ফোল্ডার",
    "Add New": "নতুন যোগ করুন",
    Size: "আকার",
    Date: "তারিখ",
    "back to parent folder": "প্যারেন্ট ফোল্ডারে ফিরে যান",
    Download: "ডাউনলোড করুন",
    Type: "ধরন",
    Information: "তথ্য",
    Files: "ফাইলসমূহ",
    Table: "টেবিল",
    Cards: "কার্ড",
    Total: "মোট",
    "Are you sure ?": "আপনি কি নিশ্চিত?",
    Details: "বিস্তারিত",
    "Enter a new name": "নতুন নাম লিখুন",
    Add: "যোগ করুন",
    "Select something": "কিছু নির্বাচন করুন",
    "Download file": "ফাইল ডাউনলোড করুন",
    Preview: "প্রিভিউ",
    Refresh: "রিফ্রেশ",
    "Are you sure you want to exit without saving?": "আপনি কি সংরক্ষণ না করে বের হতে চান?",
    "Save before closing?": "বন্ধ করার আগে সংরক্ষণ করবেন?",
    Copy: "কপি করুন",
    Cut: "কাট করুন",
    Paste: "পেস্ট করুন",
    "Deleting...": "মুছে ফেলা হচ্ছে...",
    "Copying...": "কপি করা হচ্ছে...",
    "Moving...": "সরানো হচ্ছে...",
    Folders: "ফোল্ডারসমূহ",
    "Search results": "অনুসন্ধানের ফলাফল",
    "Search results in": "ফলাফল এখানে",
    "Search files and folders": "ফাইল ও ফোল্ডার অনুসন্ধান করুন",
    "Add new file": "নতুন ফাইল যোগ করুন",
    "Add new folder": "নতুন ফোল্ডার যোগ করুন",
    "Upload file": "ফাইল আপলোড করুন",
    folder: "ফোল্ডার",
    file: "ফাইল",
    archive: "আর্কাইভ",
    audio: "অডিও",
    image: "ছবি",
    video: "ভিডিও",
    code: "কোড",
    document: "ডকুমেন্ট",
    of: "এর",
    used: "ব্যবহৃত",
    "Open item location": "আইটেম অবস্থান খুলুন",
    "Are you sure you want to delete": "আপনি কি নিশ্চিতভাবে মুছে ফেলতে চান",
    "these items:": "এই আইটেমগুলো:",
    "this item:": "এই আইটেমটি:",
    "Delete files": "ফাইলগুলো মুছে ফেলুন",
    and: "এবং",
    "more file(s)": "আরও ফাইল(গুলি)",
    "Close the editor": "এডিটর বন্ধ করুন",
    "Close this file": "এই ফাইলটি বন্ধ করুন",
    "Owner": "মালিক",
    "Permissions": "অনুমতিসমূহ",
    "Change Permissions": "অনুমতি পরিবর্তন করুন",
    "Set": "সেট করুন",
    "Extract": "এক্সট্রাক্ট করুন",
    "Extract directory": "ডিরেক্টরি এক্সট্রাক্ট করুন",
    "Extracting...": "এক্সট্রাক্ট করা হচ্ছে...",
    "Compress": "কমপ্রেস করুন",
    "Compressing...": "কমপ্রেস করা হচ্ছে...",
};