var en = {
    Save: "Salva",
    "Save all": "Salva tutto",
    Rename: "Rinomina",
    Open: "Apri",
    Edit: "Modifica",
    Delete: "Elimina",
    Folder: "Cartella",
    "Add New": "Aggiungi Nuovo",
    Size: "Dimensione",
    Date: "Data",
    "back to parent folder": "torna alla cartella padre",
    Download: "Scarica",
    Type: "Tipo",
    Information: "Informazione",
    Files: "Files",
    Table: "Tabella",
    Cards: "Carte",
    Total: "Totale",
    "Are you sure ?": "Sei sicuro ?",
    Details: "Dettagli",
    "Enter a new name": "Inserisci un nuovo nome",
    Add: "Aggiungi",
    "Select something": "Seleziona qualcosa",
    "Download file": "Scarica file",
    Preview: "Anteprima",
    Refresh: "Ricarica",
    "Are you sure you want to exit without saving?": "Sei sicuro di voler uscire senza salvare?",
    "Save before closing?": "Salvare prima di chiudere?",
    Copy: "Copia",
    Cut: "Taglia",
    Paste: "Incolla",
    "Deleting...": "Eliminazione in corso...",
    "Copying...": "Copia in corso...",
    "Moving...": "Spostamento in corso...",
    Folders: "Cartelle",
    "Search results": "Risultati di ricerca",
    "Search results in": "Cerca risultati in",
    "Search files and folders": "Cerca file e cartelle",
    "Add new file": "Aggiungi nuovo file",
    "Add new folder": "Aggiungi nuova cartella",
    "Upload file": "Carica file",
    folder: "cartella",
    file: "file",
    archive: "archivio",
    audio: "audio",
    image: "immagine",
    video: "video",
    code: "codice",
    document: "documento",
    of: "di",
    used: "usato",
    "Open item location": "Apri percorso elemento",
    "Are you sure you want to delete": "Sei sicuro di voler eliminare",
    "these items:": "questi elementi:",
    "this item:": "questo elemento:",
    "Delete files": "Cancella file",
    and: "e",
    "more file(s)": "più file",
    "Close the editor": "Chiudi l'editor",
    "Close this file": "Chiudi questo file",
    "Owner": "Proprietario",
    "Permissions": "Permessi",
    "Change Permissions": "Cambia Permessi",
    "Set": "Imposta",
    "Extract": "Estrai",
    "Extract directory": "Percorso di destinazione",
    "Extracting...": "Estrazione in corso...",
    "Compress": "Comprimi",
    "Compressing...": "Compressione in corso...",
};
