var tr = {
    Save: "Kaydet",
    "Save all": "Tümünü kaydet",
    Rename: "Yeniden adlandır",
    Open: "Aç",
    Edit: "Düzenle",
    Delete: "Sil",
    Folder: "Dosya",
    "Add New": "Yeni ekle",
    Size: "Boyut",
    Date: "Tarih",
    "back to parent folder": "Üst klasöre dön",
    Download: "İndir",
    Type: "Tür",
    Information: "Bilgiler",
    Files: "Dosyalar",
    Table: "Tablo",
    Cards: "Kartlar",
    Total: "Toplam",
    "Are you sure ?": "Emin misiniz?",
    Details: "Ayrıntılar",
    "Enter a new name": "Yeni adı yazın",
    Add: "Ekle",
    "Select something": "Ögeleri seçin",
    "Download file": "Dosyayı indir",
    Preview: "Ön izleme",
    Refresh: "Yenile",
    "Are you sure you want to exit without saving?": "Kaydetmeden çıkmak istediğinize emin misiniz?",
    "Save before closing?": "Kapatmadan önce kaydedilsin mi?",
    Copy: "Kopyala",
    Cut: "Kes",
    Paste: "Yapıştır",
    "Deleting...": "Siliniyor...",
    "Copying...": "Kopyalanıyor...",
    "Moving...": "Taşınıyor...",
    Folders: "Klasörler",
    "Search results": "Arama sonuçları",
    "Search results in": "Şuradaki arama sonuçları",
    "Search files and folders": "Dosya ve klasör ara",
    "Add new file": "Yeni dosya ekle",
    "Add new folder": "Yeni klasör ekle",
    "Upload file": "Dosya yükle",
    folder: "klasör",
    file: "dosya",
    archive: "arşiv",
    audio: "ses",
    image: "görsel",
    video: "video",
    code: "kod",
    document: "belge",
    of: "/",
    used: "kullanılmış",
    "Open item location": "Öge konumunu aç",
    "Are you sure you want to delete": "Silmek istediğinize emin misiniz",
    "these items:": "şu ögeleri:",
    "this item:": "şu ögeyi:",
    "Delete files": "Dosyaları sil",
    and: "ve",
    "more file(s)": "diğer dosya(lar)",
    "Close the editor": "Düzenleyiciyi kapat",
    "Close this file": "Bu dosyayı kapat",
    "Owner": "Sahibi",
    "Permissions": "İzinler",
    "Change Permissions": "İzinleri değiştir",
    "Set": "Ayarla",
    "Extract": "Ayıkla",
    "Extract directory": "Klasörü ayıkla",
    "Extracting...": "Ayıklanıyor...",
    "Compress": "Sıkıştır",
    "Compressing...": "Sıkıştırılıyor...",
};