var tr = {
    Save: "Kaydet",
    "Save all": "Tümünü Kaydet",
    Rename: "Adı Değiştir",
    Open: "Aç",
    Edit: "Düzenle",
    Delete: "Sil",
    Folder: "Dosya",
    "Add New": "Yeni ...",
    Size: "Boyut",
    Date: "Tarih",
    "back to parent folder": "Bir Üst Klasöre Dön",
    Download: "İndir",
    Type: "Tür",
    Information: "Bilgiler",
    Files: "Dosyalar",
    Table: "Tablo",
    Cards: "Kartlar",
    Total: "Toplam",
    "Are you sure ?": "emin misiniz?",
    Details: "Detaylar",
    "Enter a new name": "Yeni Adı Yazın",
    Add: "Ekle",
    "Select something": "Ögeleri Seçin",
    "Download file": "Dosyayı İndir",
    Preview: "Önizleme",
    Refresh: "Yenile",
    "Are you sure you want to exit without saving?": "kaydetmeden çıkmak istediğinize emin misiniz?",
    "Save before closing?": "kapatmadan önce kaydetmek ister misiniz?",
    Copy: "Kopyala",
    Cut: "Kes",
    Paste: "Yapıştır",
    "Deleting...": "siliniyor ...",
    "Copying...": "kopyalanıyor ...",
    "Moving...": "taşınıyor ...",
    Folders: "Klasörler",
    "Search results": "Arama Sonuçları",
    "Search results in": "Arama Sonuçları :",
    "Search files and folders": "Dosya ve Klasörleri Ara",
    "Add new file": "Dosya Oluştur",
    "Add new folder": "Klasör Oluştur",
    "Upload file": "Dosya Yükle",
    folder: "klasör",
    file: "dosya",
    archive: "arşiv",
    audio: "ses",
    image: "resim",
    video: "video",
    code: "kod",
    document: "belge",
    of: "/",
    used: "kullanılmış",
    "Open item location": "Dosya Konumunu Aç",
    "Are you sure you want to delete": "silmek istediğinize emin misiniz?",
    "these items:": "alttaki dosyaları:",
    "this item:": "alttaki dosyayı:",
    "Delete files": "Dosyaları Sil",
    and: "ve",
    "more file(s)": "Diğer Dosya(lar)",
    "Close the editor": "Kapat",
    "Close this file": "Kapat",
    "Owner": "Sahip",
    "Permissions": "İzinler",
    "Change Permissions": "İzinleri Değiştir",
    "Set": "Ayarla",
    "Extract": "Çıkar",
    "Extract directory": "Klasöre Çıkar",
    "Extracting...": "çıkarılıyor ...",
    "Compress": "Arşivle",
    "Compressing...": "arşivleniyor ...",
};