var tr = {
    Save: "Kaydet",
    "Save all": "Hepsini Kaydet",
    Rename: "Yeniden isimlendir",
    Open: "Aç",
    Edit: "Düzenle",
    Delete: "Sil",
    Folder: "Dosya",
    "Add New": "Yeni Ekle",
    Size: "Boyut",
    Date: "Tarih",
    "back to parent folder": "Ana klasöre geri dön",
    Download: "İndir",
    Type: "Tip",
    Information: "Bilgi",
    Files: "Dosyalar",
    Table: "Tablo",
    Cards: "Kartlar",
    Total: "Toplam",
    "Are you sure ?": "Emin misin?",
    Details: "Detaylar",
    "Enter a new name": "Yeni bir isim girin",
    Add: "Ekle",
    "Select something": "Birşeyler seç",
    "Download file": "Dosyayı indir",
    Preview: "Önizleme",
    Refresh: "Yenile",
    "Are you sure you want to exit without saving?": "Kaydetmeden çıkmak istediğine emin misin?",
    "Save before closing?": "Kapatmadan önce kaydet?",
    Copy: "Kopya",
    Cut: "Kes",
    Paste: "Yapıştır",
    "Deleting...": "Siliyor...",
    "Copying...": "Kopyalıyor...",
    "Moving...": "Taşıyor...",
    Folders: "Klasörler",
    "Search results": "Arama sonuçları",
    "Search results in": "Arama sonuçları",
    "Search files and folders": "Dosya ve Klasör ara",
    "Add new file": "Yeni dosya ekle",
    "Add new folder": "Yeni klasör ekle",
    "Upload file": "Dosya yükle",
    folder: "klasör",
    file: "dosya",
    archive: "arşiv",
    audio: "ses",
    image: "resim",
    video: "video",
    code: "kod",
    document: "döküman",
    of: "dan",
    used: "kullanılan",
    "Open item location": "Öğe konumunu aç",
    "Are you sure you want to delete": "Silmek istediğine emin misin",
    "these items:": "bu öğeler:",
    "this item:": "bu öğe:",
    "Delete files": "Dosyaları sil",
    and: "ve",
    "more file(s)": "daha fazla dosya(lar)",
    "Close the editor": "Editörü kapat",
    "Close this file": "Bu dosyayı kapat",
    "Owner": "Sahip",
    "Permissions": "Yetkiler",
    "Change Permissions": "Yetkileri değiştir",
    "Set": "Ata",
    "Extract": "Dışa aktar",
    "Extract directory": "Klasörü dışarıya aktar",
    "Extracting...": "Dışarı aktarılıyor...",
    "Compress": "Sıkıştırma",
    "Compressing...": "Sıkıştırılıyor...",
};