var da = {
    Save: "Gem",
    "Save all": "Gem alle",
    Rename: "Omdøb",
    Open: "Åbn",
    Edit: "Rediger",
    Delete: "Slet",
    Folder: "Mappe",
    "Add New": "Tilføj ny",
    Size: "Størrelse",
    Date: "Dato",
    "back to parent folder": "tilbage til forældremappe",
    Download: "Download",
    Type: "Type",
    Information: "Information",
    Files: "Filer",
    Table: "Tabel",
    Cards: "Kort",
    Total: "Total",
    "Are you sure ?": "Er du sikker ?",
    Details: "Detaljer",
    "Enter a new name": "Indtast et nyt navn",
    Add: "Tilføj",
    "Select something": "Vælg noget",
    "Download file": "Download fil",
    Preview: "Forhåndsvis",
    Refresh: "Opdater",
    "Are you sure you want to exit without saving?": "Er du sikker på du vil lukke uden af gemme?",
    "Save before closing?": "Gem før du lukker?",
    Copy: "Kopier",
    Cut: "Klip",
    Paste: "Indsæt",
    "Deleting...": "Sletter...",
    "Copying...": "Kopierer...",
    "Moving...": "Flytter...",
    Folders: "Mapper",
    "Search results": "Søgeresultater",
    "Search results in": "Søgeresultater i",
    "Search files and folders": "Søg efter filer og mapper",
    "Add new file": "Tilføj ny fil",
    "Add new folder": "Tilføj ny mappe",
    "Upload file": "Upload fil",
    folder: "mappe",
    file: "fil",
    archive: "arkiv",
    audio: "lyd",
    image: "billede",
    video: "video",
    code: "kode",
    document: "dokument",
    of: "af",
    used: "brugt",
    "Open item location": "Åbn placering for element",
    "Are you sure you want to delete": "Er du sikker på du vil slette",
    "these items:": "disse elementer:",
    "this item:": "dette element:",
    "Delete files": "Slet filer",
    and: "og",
    "more file(s)": "flere fil(er)",
    "Close the editor": "Luk editoren",
    "Close this file": "Luk denne fil",
    "Owner": "Ejer",
    "Permissions": "Rettigheder",
    "Change Permissions": "Skift rettigheder",
    "Set": "Sæt",
    "Extract": "Pak ud",
    "Extract directory": "Pak bibliotek ud",
    "Extracting...": "Pakker ud...",
    "Compress": "Komprimer",
    "Compressing...": "Komprimerer...",
};