var id = {
    Save: "Uložit",
    "Save all": "Uložit vše",
    Rename: "Přejmenovat",
    Open: "Otevřít",
    Edit: "Upravit",
    Delete: "Smazat",
    Folder: "Složka",
    "Add New": "Přidat nový",
    Size: "Velikost",
    Date: "Datum",
    "back to parent folder": "Zpět do nadřazené složky",
    Download: "Stáhnout",
    Type: "Typ",
    Information: "Informace",
    Files: "Soubory",
    Table: "Tabulka",
    Cards: "Karty",
    Total: "Celkem",
    "Are you sure ?": "Jste si jisti?",
    Details: "Podrobnosti",
    "Enter a new name": "Zadejte nový název",
    Add: "Přidat",
    "Select something": "Vyberte nejprve",
    "Download file": "Stáhnout soubor",
    Preview: "Náhled",
    Refresh: "Obnovit",
    "Are you sure you want to exit without saving?": "Jste si jisti, že chcete odejít bez uložení?",
    "Save before closing?": "Uložit před zavřením?",
    Copy: "Kopírovat",
    Cut: "Vyjmout",
    Paste: "Vložit",
    "Deleting...": "Mažu...",
    "Copying...": "Kopíruji...",
    "Moving...": "Přesunuji...",
    Folders: "Složky",
    "Search results": "Výsledky hledání",
    "Search results in": "Výsledky hledání pro",
    "Search files and folders": "Hledat soubory a složky",
    "Add new file": "Přidat nový soubor",
    "Add new folder": "Přidat novou složku",
    "Upload file": "Nahrát soubor",
    folder: "složka",
    file: "soubor",
    archive: "archiv",
    audio: "zvuk",
    image: "obrázek",
    video: "video",
    code: "kód",
    document: "dokument",
    of: "z",
    used: "použito",
    "Open item location": "Otevřít umístění položky",
    "Are you sure you want to delete": "Jste si jisti, že chcete smazat",
    "these items:": "tyto položky:",
    "this item:": "tuto položku:",
    "Delete files": "Smazat soubory",
    and: "a",
    "more file(s)": "dalších souborů",
    "Close the editor": "Zavřít editor",
    "Close this file": "Zavřít tento soubor",
    "Owner": "Vlastník",
    "Permissions": "Oprávnění",
    "Change Permissions": "Změnit oprávnění",
    "Set": "Nastavit",
    "Extract": "Rozbalit",
    "Extract directory": "Rozbalit složku",
    "Extracting...": "Probíhá rozbalování...",
    "Compress": "Komprimovat",
    "Compressing...": "Probíhá komprimace..."
};
