var nl = {
    Save: "Opslaan",
    "Save all": "Alles opslaan",
    Rename: "Hernoemen",
    Open: "Open",
    Edit: "Bewerk",
    Delete: "Verwijder",
    Folder: "Mapp",
    "Add New": "Nieuwe toevoegen",
    Size: "Grootte",
    Date: "Datum",
    "back to parent folder": "terug naar bovenliggende map",
    Download: "Download",
    Type: "Type",
    Information: "Informatie",
    Files: "Bestanden",
    Table: "Tabel",
    Cards: "Kaarten",
    Total: "Totaal",
    "Are you sure ?": "Weet je het zeker?",
    Details: "Details",
    "Enter a new name": "Vul een nieuwe naam in",
    Add: "Toevoegen",
    "Select something": "Selecteer iets",
    "Download file": "Download bestand",
    Preview: "Voorbeeld",
    Refresh: "Vernieuwen",
    "Are you sure you want to exit without saving?": "Weet je zeker dat je wilt afsluiten zonder op te slaan?",
    "Save before closing?": "Opslaan voor afsluiten?",
    Copy: "Kopiëren",
    Cut: "Knippen",
    Paste: "Plakken",
    "Deleting...": "Verwijderen...",
    "Copying...": "Kopiëren...",
    "Moving...": "Verplaatsen...",
    Folders: "Mappen",
    "Search results": "Zoekresultaten",
    "Search results in": "Zoekresultaten in",
    "Search files and folders": "Zoek bestanden en mappen",
    "Add new file": "Nieuw bestand toevoegen",
    "Add new folder": "Nieuwe map toevoegen",
    "Upload file": "Upload bestand",
    folder: "map",
    file: "bestand",
    archive: "archief",
    audio: "audio",
    image: "afbeelding",
    video: "video",
    code: "code",
    document: "document",
    of: "van",
    used: "gebruikt",
    "Open item location": "Open item locatie",
    "Are you sure you want to delete": "Weet je zeker dat je dit bestand wilt verwijderen",
    "these items:": "deze items:",
    "this item:": "dit item:",
    "Delete files": "Verwijder bestanden",
    and: "en",
    "more file(s)": "meer bestand(en)",
    "Close the editor": "Sluit de editor",
    "Close this file": "sluit dit bestand",
    "Owner": "Eigenaar",
    "Permissions": "Rechten",
    "Change Permissions": "Verander rechten",
    "Set": "Instellen",
    "Extract": "Uitpakken",
    "Extract directory": "Map uitpakken",
    "Extracting...": "Uitpakken...",
    "Compress": "Comprimeren",
    "Compressing...": "Comprimeren...",
};