var id = {
    Save: "Simpan",
    "Save all": "Simpan semua",
    Rename: "Ubah nama",
    Open: "Buka",
    Edit: "Ubah",
    Delete: "Hapus",
    Folder: "Folder",
    "Add New": "Tambah Baru",
    Size: "Ukuran",
    Date: "Tanggal",
    "back to parent folder": "kembali ke folder induk",
    Download: "Unduh",
    Type: "Tipe",
    Information: "Informasi",
    Files: "File",
    Table: "Tabel",
    Cards: "Kartu",
    Total: "Total",
    "Are you sure ?": "Apakah Anda yakin?",
    Details: "Rincian",
    "Enter a new name": "Masukkan nama baru",
    Add: "Tambah",
    "Select something": "Pilih terlebih dahulu",
    "Download file": "Unduh file",
    Preview: "Pratinjau",
    Refresh: "Segarkan",
    "Are you sure you want to exit without saving?": "Apakah Anda yakin ingin keluar tanpa menyimpannya?"
    "Save before closing?": "Simpan sebelum ditutup?",
    Copy: "Salin",
    Cut: "Potong",
    Paste: "Tempel",
    "Deleting...": "Menghapus...",
    "Copying...": "Menyalin...",
    "Moving...": "Memindahkan...",
    Folders: "Folder",
    "Search results": "Hasil pencarian",
    "Search results in": "Hasil pencarian untuk",
    "Search files and folders": "Cari file dan folder",
    "Add new file": "Tambah file baru",
    "Add new folder": "Tambah folder baru",
    "Upload file": "Unggah file",
    folder: "folder",
    file: "file",
    archive: "arsip",
    audio: "audio",
    image: "gambar",
    video: "video",
    code: "kode",
    document: "dokumen",
    of: "dari",
    used: "terpakai",
    "Open item location": "Buka lokasi item",
    "Are you sure you want to delete": "Apakah Anda yakin ingin menghapusnya?",
    "these items:": "item-item ini:",
    "this item:": "item ini:",
    "Delete files": "Hapus file",
    and: "dan",
    "more file(s)": "file lainnya",
    "Close the editor": "Tutup editornya",
    "Close this file": "Tutup file ini",
    "Owner": "Pemilik",
    "Permissions": "Izin",
    "Change Permissions": "Ubah Izin",
    "Set": "Terapkan",
    "Extract": "Ekstrak",
    "Extract directory": "Ekstrak direktori",
    "Extracting...": "Mengekstrak...",
    "Compress": "Kompres",
    "Compressing...": "Mengompres...",
};