var fi = {
    Save: "Tallenna",
    "Save all": "Tallenna kaikki",
    Rename: "Nimeä uudelleen",
    Open: "Avaa",
    Edit: "Muokkaa",
    Delete: "Poista",
    Folder: "Kansio",
    "Add New": "Lisää uusi",
    Size: "Koko",
    Date: "Aika",
    "back to parent folder": "takaisin ylempään kansioon",
    Download: "Lataa",
    Type: "Tyyppi",
    Information: "Tiedot",
    Files: "Tiedostot",
    Table: "Taulukko",
    Cards: "Kortit",
    Total: "Yhteensä",
    "Are you sure ?": "Oletko varma?",
    Details: "Tiedot",
    "Enter a new name": "Syötä uusi nimi",
    Add: "Lisää",
    "Select something": "Valitse jotakin",
    "Download file": "DownLataa tiedosto",
    Preview: "Esikatsele",
    Refresh: "Päivitä",
    "Are you sure you want to exit without saving?": "Haluatko varmasti poistua tallentamatta muutoksia?",
    "Save before closing?": "Tallenna ennen sulkemista?",
    Copy: "Kopioi",
    Cut: "Leikkaa",
    Paste: "Liitä",
    "Deleting...": "Poistetaan...",
    "Copying...": "Kopioidaan...",
    "Moving...": "Siirretään...",
    Folders: "Kansiot",
    "Search results": "Hakutulokset",
    "Search results in": "Hakutulokset kohteessa",
    "Search files and folders": "Etsi tiedostoja tai kansioita",
    "Add new file": "Lisää uusi tiedosto",
    "Add new folder": "Lisää uusi kansio",
    "Upload file": "Lataa tiedosto palvelimelle",
    folder: "kansio",
    file: "tiedosto",
    archive: "arkisto",
    audio: "ääni",
    image: "kuva",
    video: "video",
    code: "koodi",
    document: "dokumentti",
    of: "/",
    used: "käytetty",
    "Open item location": "Avaa kohteen sijainti",
    "Are you sure you want to delete": "Haluatko varmasti poistaa",
    "these items:": "nämä kohteet:",
    "this item:": "tämän kohteen:",
    "Delete files": "Poista tiedostot",
    and: "ja",
    "more file(s)": "tiedosto(a) lisää",
    "Close the editor": "Sulje muokkain",
    "Close this file": "Sulje tämä tiedosto",
    "Owner": "Omistaja",
    "Permissions": "Oikeudet",
    "Change Permissions": "Muokkaa oikeuksia",
    "Set": "Aseta",
    "Extract": "Pura",
    "Extract directory": "Purkuhakemisto",
    "Extracting...": "Puretaan...",
    "Compress": "Pakkaa",
    "Compressing...": "Pakataan...",
};