var ru = {
    Save: "Сохранить",
    "Save all": "Сохранить всё",
    Rename: "Переименовать",
    Open: "Открыть",
    Edit: "Редактировать",
    Delete: "Удалить",
    Folder: "Папка",
    "Add New": "Добавить",
    Size: "Размер",
    Date: "Дата",
    "back to parent folder": "назад в родительскую папку",
    Download: "Скачать",
    Type: "Тип",
    Information: "Сведения",
    Files: "Файлы",
    Table: "Таблица",
    Cards: "Карты",
    Total: "Итого",
    "Are you sure ?": "Вы уверены ?",
    Details: "Детали",
    "Enter a new name": "Введите новое имя",
    Add: "Добавить",
    "Select something": "Выберите что-то",
    "Download file": "Скачать файл",
    Preview: "Превью",
    Refresh: "Обновить",
    "Are you sure you want to exit without saving?": "Вы действительно хотите выйти без сохранения?",
    "Save before closing?": "Сохранить перед закрытием?",
    Copy: "Копировать",
    Cut: "Вырезать",
    Paste: "Вставить",
    "Deleting...": "Удаление...",
    "Copying...": "Копирование...",
    "Moving...": "Перемещение ...",
    Folders: "Папки",
    "Search results": "Результаты поиска",
    "Search results in": "Результаты поиска в",
    "Search files and folders": "Поиск файлов и папок",
    "Add new file": "Новый файл",
    "Add new folder": "Новая папка",
    "Upload file": "Загрузить файл",
    folder: "папка",
    file: "файл",
    archive: "архив",
    audio: "аудио",
    image: "изображение",
    video: "видео",
    code: "код",
    document: "документ",
    of: "из",
    used: "используется",
    "Open item location": "Открыть расположение элемента",
    "Are you sure you want to delete": "Вы уверены, что хотите удалить",
    "these items:": "эти пункты:",
    "this item:": "этот пункт:",
    "Delete files": "Удалить файлы",
    and: "и",
    "more file(s)": "больше файлов",
    "Close the editor": "Закрыть редактор",
    "Close this file": "Закрыть этот файл",
    "Owner": "Владелец",
    "Permissions": "Права доступа",
    "Change Permissions": "Изменить права доступа",
    "Set": "Установить",
    "Extract": "Извлечь",
    "Extract directory": "Извлечь каталог",
    "Extracting...": "Извлечение...",
    "Compress": "Сжать",
    "Compressing...": "Сжатие...",
};