var fr = {
    Save: "Sauvegarder",
    "Save all": "Tout sauvegarder",
    Rename: "Renommer",
    Open: "Ouvrir",
    Edit: "Éditer",
    Delete: "Supprimer",
    Folder: "Dossier",
    "Add New": "Ajouter nouveau",
    Size: "Taille",
    Date: "Date",
    "back to parent folder": "retour au dossier parent",
    Download: "Télécharger",
    Type: "Type",
    Information: "Information",
    Files: "Fichiers",
    Table: "Table",
    Cards: "Cartes",
    Total: "Total",
    "Are you sure ?": "Êtes-vous sûr(e) ?",
    Details: "Détails",
    "Enter a new name": "Entrer un nouveau nom",
    Add: "Ajouter",
    "Select something": "Sélectionner quelque chose",
    "Download file": "Télécharger fichier",
    Preview: "Prévisualiser",
    Refresh: "Rafraîchir",
    "Are you sure you want to exit without saving?": "Êtes-vous sûr(e) de vouloir quitter sans sauvegarder?",
    "Save before closing?": "Sauvegarder avant de quitter?",
    Copy: "Copier",
    Cut: "Couper",
    Paste: "Coller",
    "Deleting...": "Suppression...",
    "Copying...": "Copie...",
    "Moving...": "Déplacement...",
    Folders: "Fichiers",
    "Search results": "Résultats de recherche",
    "Search results in": "Résultats de recherche dans",
    "Search files and folders": "Rechercher dans les fichiers et dossiers",
    "Add new file": "Nouveau fichier",
    "Add new folder": "Nouveau dossier",
    "Upload file": "Charger fichier",
    folder: "dossier",
    file: "fichier",
    archive: "archive",
    audio: "audio",
    image: "image",
    video: "vidéo",
    code: "code",
    document: "document",
    of: "de",
    used: "utilisé",
    "Open item location": "Ouvrir le dossier parent",
    "Are you sure you want to delete": "Êtes-vous sûr(e) de vouloir supprimer",
    "these items:": "ces éléments:",
    "this item:": "cet élément:",
    "Delete files": "Supprimer des fichiers",
    and: "et",
    "more file(s)": "plus de fichier(s)",
    "Close the editor": "Fermer l'éditeur",
    "Close this file": "Fermer le fichier",
    "Owner": "Propriétaire",
    "Permissions": "Permissions",
    "Change Permissions": "Changer permissions",
    "Set": "Définir",
    "Extract": "Extraire",
    "Extract directory": "Extraire répertoire",
    "Extracting...": "Extraction...",
    "Compress": "Compresser",
    "Compressing...": "Compression...",
};