var he = {
    Save: "שמירה",
    "Save all": "שמירה של כולם",
    Rename: "שינוי שם",
    Open: "פתיחה",
    Edit: "עריכה",
    Delete: "מחיקה",
    Folder: "תיקייה",
    "Add New": "יצירת חדש",
    Size: "גודל",
    Date: "תאריך",
    "back to parent folder": "חזרה לתיקיית האב",
    Download: "הורדה",
    Type: "סוג",
    Information: "מידע",
    Files: "קבצים",
    Table: "טבלה",
    Cards: "כרטיסים",
    Total: "סה\"כ",
    "Are you sure ?": "בטוחים?",
    Details: "פרטים",
    "Enter a new name": "הזנת שם חדש",
    Add: "הוספה",
    "Select something": "בחרו משהו",
    "Download file": "הורדת קובץ",
    Preview: "תצוגה מקדימה",
    Refresh: "רענון",
    "Are you sure you want to exit without saving?": "בטוח לצאת ללא שמירה?",
    "Save before closing?": "לשמור לפני סגירה?",
    Copy: "העתקה",
    Cut: "גזירה",
    Paste: "הדבקה",
    "Deleting...": "מוחק...",
    "Copying...": "מעתיק...",
    "Moving...": "מעביר...",
    Folders: "תיקייות",
    "Search results": "תוצאות חיפוש",
    "Search results in": "תוצאות חיפוש ב:",
    "Search files and folders": "חיפוש תיקייות וקבצים",
    "Add new file": "יצירת קובץ",
    "Add new folder": "יצירת תיקייה",
    "Upload file": "העלאת קובץ",
    folder: "תיקייה",
    file: "קובץ",
    archive: "ארכיון",
    audio: "אודיו",
    image: "תמונה",
    video: "וידאו",
    code: "קוד",
    document: "מסמך",
    of: "של",
    used: "בשימוש",
    "Open item location": "פתיחת מיקום קובץ",
    "Are you sure you want to delete": "בטוח למחוק",
    "these items:": "פריטים אלו:",
    "this item:": "פריט זה:",
    "Delete files": "מחיקת קבצים",
    and: "ו",
    "more file(s)": "עוד קבצים",
    "Close the editor": "סגירת העורך",
    "Close this file": "סגירת קובץ זה",
    "Owner": "בעלים",
    "Permissions": "הרשאות",
    "Change Permissions": "שינוי הרשאות",
    "Set": "הגדרה",
    "Extract": "חילוץ",
    "Extract directory": "חילוץ תיקייה",
    "Extracting...": "מחלץ...",
    "Compress": "דחיסה",
    "Compressing...": "דוחס...",
};
