var th = {
    Save: "บันทึก",
    "Save all": "บันทึกทั้งหมด",
    Rename: "เปลี่ยนชื่อ",
    Open: "เปิด",
    Edit: "แก้ไข",
    Delete: "ลบ",
    Folder: "โฟลเดอร์",
    "Add New": "เพิ่มใหม่",
    Size: "ขนาด",
    Date: "วันที่",
    "back to parent folder": "กลับไปยังโฟลเดอร์หลัก",
    Download: "ดาวน์โหลด",
    Type: "ประเภท",
    Information: "ข้อมูล",
    Files: "ไฟล์",
    Table: "ตาราง",
    Cards: "การ์ด",
    Total: "ทั้งหมด",
    "Are you sure ?": "คุณแน่ใจหรือ?",
    Details: "รายละเอียด",
    "Enter a new name": "ใส่ชื่อใหม่",
    Add: "เพิ่ม",
    "Select something": "เลือกบางอย่าง",
    "Download file": "ดาวน์โหลดไฟล์",
    Preview: "ดูตัวอย่าง",
    Refresh: "รีเฟรช",
    "Are you sure you want to exit without saving?": "คุณแน่ใจหรือว่าต้องการออกโดยไม่บันทึก?",
    "Save before closing?": "บันทึกก่อนปิดหรือไม่?",
    Copy: "คัดลอก",
    Cut: "ตัด",
    Paste: "วาง",
    "Deleting...": "กำลังลบ...",
    "Copying...": "กำลังคัดลอก...",
    "Moving...": "กำลังย้าย...",
    Folders: "โฟลเดอร์",
    "Search results": "ผลการค้นหา",
    "Search results in": "ผลการค้นหาใน",
    "Search files and folders": "ค้นหาไฟล์และโฟลเดอร์",
    "Add new file": "เพิ่มไฟล์ใหม่",
    "Add new folder": "เพิ่มโฟลเดอร์ใหม่",
    "Upload file": "อัปโหลดไฟล์",
    folder: "โฟลเดอร์",
    file: "ไฟล์",
    archive: "คลัง",
    audio: "เสียง",
    image: "รูปภาพ",
    video: "วิดีโอ",
    code: "โค้ด",
    document: "เอกสาร",
    of: "ของ",
    used: "ใช้แล้ว",
    "Open item location": "เปิดตำแหน่งของรายการ",
    "Are you sure you want to delete": "คุณแน่ใจหรือว่าต้องการลบ",
    "these items:": "รายการเหล่านี้:",
    "this item:": "รายการนี้:",
    "Delete files": "ลบไฟล์",
    and: "และ",
    "more file(s)": "ไฟล์เพิ่มเติม",
    "Close the editor": "ปิดตัวแก้ไข",
    "Close this file": "ปิดไฟล์นี้",
    "Owner": "เจ้าของ",
    "Permissions": "สิทธิ์",
    "Change Permissions": "เปลี่ยนสิทธิ์",
    "Set": "ตั้งค่า",
    "Extract": "แยกไฟล์",
    "Extract directory": "แยกไดเรกทอรี",
    "Extracting...": "กำลังแยกไฟล์...",
    "Compress": "บีบอัด",
    "Compressing...": "กำลังบีบอัด...",
};
