var es = {
    Save: "Guardar",
    "Save all": "Guardar todo",
    Rename: "Renombrar",
    Open: "Abrir",
    Edit: "Editar",
    Delete: "Borrar",
    Folder: "Carpeta",
    "Add New": "Añadir nuevo",
    Size: "Tamaño",
    Date: "Fecha",
    "back to parent folder": "volver al directorio padre",
    Download: "Descargar",
    Type: "Tipo",
    Information: "Información",
    Files: "Archivos",
    Table: "Tabla",
    Cards: "Tarjetas",
    Total: "Total",
    "Are you sure ?": "¿Estás seguro?",
    Details: "Detalles",
    "Enter a new name": "Introduzca un nombre nuevo",
    Add: "Añadir",
    "Select something": "Seleccione algo",
    "Download file": "Descargar archivo",
    Preview: "Vista previa",
    Refresh: "Actualizar",
    "Are you sure you want to exit without saving?": "¿Está seguro que quiere salir sin guardar?",
    "Save before closing?": "¿Guardar antes de salir?",
    Copy: "Copiar",
    Cut: "Cortar",
    Paste: "Pegar",
    "Deleting...": "Eliminando...",
    "Copying...": "Copiando...",
    "Moving...": "Moviendo...",
    Folders: "Carpetas",
    "Search results": "Resultados de búsqueda",
    "Search results in": "Resultados de búsqueda en",
    "Search files and folders": "Buscar archivos y carpetas",
    "Add new file": "Añadir archivo nuevo",
    "Add new folder": "Añadir una nueva carpeta",
    "Upload file": "Subir archivo",
    folder: "carpeta",
    file: "archivo",
    archive: "archivo",
    audio: "audio",
    image: "imagen",
    video: "vídeo",
    code: "código",
    document: "documento",
    of: "de",
    used: "usado",
    "Open item location": "Abrir ubicación del elemento",
    "Are you sure you want to delete": "¿Estás seguro de que quieres eliminar?",
    "these items:": "estos elementos:",
    "this item:": "este elemento:",
    "Delete files": "Eliminar archivos",
    and: "y",
    "more file(s)": "más archivo(s)",
    "Close the editor": "Cerrar el editor",
    "Close this file": "Cerrar este archivo",
    "Owner": "Propietario",
    "Permissions": "Permisos",
    "Change Permissions": "Cambiar permisos",
    "Set": "Establecer",
    "Extract": "Extraer",
    "Extract directory": "Extraer directorio",
    "Extracting...": "Extrayendo...",
    "Compress": "Comprimir",
    "Compressing...": "Comprimiendo...",
};
