var sr_rs = {
    Save: "Ment",
    "Save all": "Mindent ment",
    Rename: "Átnevez",
    Open: "Megnyit",
    Edit: "Szerkeszt",
    Delete: "Töröl",
    Folder: "Könyvtár",
    "Add New": "Új hozzáadás",
    Size: "Méret",
    Date: "Dátum",
    "back to parent folder": "Vissza a szülő könyvtárba",
    Download: "Letölt",
    Type: "Tipp",
    Information: "Informació",
    Files: "Fájlok",
    Table: "Táblázat",
    Cards: "Kártyák",
    Total: "Összesen",
    "Are you sure ?": "Biztos?",
    Details: "Részletek",
    "Enter a new name": "Írd be az új nevet",
    Add: "Hozzáaad",
    "Select something": "Válassz valamit",
    "Download file": "Fájl letöltése",
    Preview: "Előnézet",
    Refresh: "Frissit",
    "Are you sure you want to exit without saving?": "Biztos ki akar lépni mentés nélkül?",
    "Save before closing?": "Ment bezárás előtt?",
    Copy: "Másol",
    Cut: "Kivág",
    Paste: "Beilleszt",
    "Deleting...": "Törlés...",
    "Copying...": "Másolás...",
    "Moving...": "Áthelyezés...",
    Folders: "Könyvtárak",
    "Search results": "Keresés eredénye",
    "Search results in": "Keresés eredménye a",
    "Search files and folders": "Könyvtárak és fájlok keresése",
    "Add new file": "Új fájl hozzáadása",
    "Add new folder": "Új könyvtár hozzáadása",
    "Upload file": "Fájl feltöltése",
    folder: "könyvtár",
    file: "fájl",
    archive: "archív mentés",
    audio: "audió",
    image: "kép",
    video: "videó",
    code: "kód",
    document: "dokumentum",
    of: "a",
    used: "használt",
    "Open item location": "Elemek lokációjának megnyitása",
    "Are you sure you want to delete": "Biztos törölni szeretnéd",
    "these items:": "ove ezek az elemek:",
    "this item:": "ez az elem:",
    "Delete files": "Fájlok törlése",
    and: "és",
    "more file(s)": "több fájl",
    "Close the editor": "Zárd be a szerkesztőt",
    "Close this file": "Zárd be ezt a fájlt",
    "Owner": "Tulajdnonos",
    "Permissions": "Jogosultságok",
    "Change Permissions": "Jogosultságok módosítása",
    "Set": "Beállít",
    "Extract": "Kitömörít",
    "Extract directory": "Könyvtár kitömörítése",
    "Extracting...": "Kitömörités...",
    "Compress": "Tömörít",
    "Compressing...": "Tömörítés...",
};
