var pt_BR = {
    Save: "Salvar",
    "Save all": "Salvar tudo",
    Rename: "Renomear",
    Open: "Abrir",
    Edit: "Editar",
    Delete: "Excluir",
    Folder: "Pasta",
    "Add New": "Adicionar novo",
    Size: "Tamanho",
    Date: "Encontro",
    "back to parent folder": "voltar para a pasta pai",
    Download: "Download",
    Type: "Modelo",
    Information: "Informação",
    Files: "Files",
    Table: "Mesa",
    Cards: "Cartões",
    Total: "Total",
    "Are you sure ?": "Tem certeza ?",
    Details: "Detalhes",
    "Enter a new name": "Digite um novo nome",
    Add: "Adicionar",
    "Select something": "Selecione algo",
    "Download file": "download do arquivo",
    Preview: "Visualizar",
    Refresh: "Atualizar",
    "Are you sure you want to exit without saving?": "Tem certeza de que deseja sair sem salvar?",
    "Save before closing?": "Salvar antes de fechar?",
    Copy: "cópia",
    Cut: "Corte",
    Paste: "Pasta",
    "Deleting...": "Deletando...",
    "Copying...": "Copiando...",
    "Moving...": "Movendo...",
    Folders: "Pastas",
    "Search results": "Procurar Resultados",
    "Search results in": "Resultados da pesquisa em",
    "Search files and folders": "Search files and folders",
    "Add new file": "Adicionar novo arquivo",
    "Add new folder": "Adicionar nova pasta",
    "Upload file": "Upload Arquivo",
    folder: "pasta",
    file: "file",
    archive: "arquivo",
    audio: "audio",
    image: "imagen",
    video: "video",
    code: "código",
    document: "documento",
    of: "do",
    used: "usado",
    "Open item location": "Localização do item faltando",
    "Are you sure you want to delete": "Tem certeza de que deseja excluir",
    "these items:": "esses itens:",
    "this item:": "este item:",
    "Delete files": "Deletar arquivos",
    and: "e",
    "more file(s)": "mais arquivo(s)",
    "Close the editor": "Feche o editor",
    "Close this file": "Fechar este arquivo",
    "Owner": "Proprietário",
    "Permissions": "Permissões",
    "Change Permissions": "Alterar permissões",
    "Set": "Definir",
    "Extract": "Extrair",
    "Extract directory": "Extrair diretório",
    "Extracting...": "Extraindo...",
    "Compress": "Comprimir",
    "Compressing....": "Compressão....",
};
