var en = {
    Save: "Salvar",
    "Save all": "Salvar tudo",
    Rename: "Renomear",
    Open: "Abrir",
    Edit: "Editar",
    Delete: "Excluir",
    Folder: "Pasta",
    "Add New": "Adicionar novo",
    Size: "Tamanho",
    Date: "Encontro",
    "back to parent folder": "voltar para a pasta pai",
    Download: "Download",
    Type: "Modelo",
    Information: "Informação",
    Files: "Files",
    Table: "Mesa",
    Cards: "Cartões",
    Total: "Total",
    "Are you sure ?": "Tem certeza ?",
    Details: "Detalhes",
    "Enter a new name": "Digite um novo nome",
    Add: "Adicionar",
    "Select something": "Selecione algo",
    "Download file": "download do arquivo",
    Preview: "Visualizar",
    Refresh: "Atualizar",
    "Are you sure you want to exit without saving?": "Tem certeza de que deseja sair sem salvar?",
    "Save before closing?": "Salvar antes de fechar?",
    Copy: "cópia",
    Cut: "Corte",
    Paste: "Pasta",
    "Deleting...": "Deleting...",
    "Copying...": "Copiando...",
    "Moving...": "Movendo...",
    Folders: "Folders",
    "Search results": "Search results",
    "Search results in": "Search results in",
    "Search files and folders": "Search files and folders",
    "Add new file": "Add new file",
    "Add new folder": "Add new folder",
    "Upload file": "Upload file",
    folder: "folder",
    file: "file",
    archive: "archive",
    audio: "audio",
    image: "image",
    video: "video",
    code: "code",
    document: "document",
    of: "of",
    used: "used",
    "Open item location": "Open item location",
    "Are you sure you want to delete": "Are you sure you want to delete",
    "these items:": "these items:",
    "this item:": "this item:",
    "Delete files": "Delete files",
    and: "and",
    "more file(s)": "more file(s)",
    "Close the editor": "Close the editor",
    "Close this file": "Close this file",
    "Owner": "Owner",
    "Permissions": "Permissions",
    "Change Permissions": "Change Permissions",
    "Set": "Set",
    "Extract": "Extract",
    "Extract directory": "Extract directory",
    "Extracting...": "Extracting...",
    "Compress": "Compress",
    "Compressing...": "Compressing...",
};
