var pt_BR = {
    Save: "Salvar",
    "Save all": "Salvar tudo",
    Rename: "Renomear",
    Open: "Abrir",
    Edit: "Editar",
    Delete: "Excluir",
    Folder: "Pasta",
    "Add New": "Adicionar novo",
    Size: "Tamanho",
    Date: "Data",
    "back to parent folder": "voltar para a pasta de origem",
    Download: "Baixar",
    Type: "Tipo",
    Information: "Informação",
    Files: "Arquivos",
    Table: "Tabela",
    Cards: "Cartões",
    Total: "Total",
    "Are you sure ?": "Você tem certeza?",
    Details: "Detalhes",
    "Enter a new name": "Digite o novo nome",
    Add: "Adicionar",
    "Select something": "Selecione algo",
    "Download file": "Baixar arquivo",
    Preview: "Visualizar",
    Refresh: "Atualizar",
    "Are you sure you want to exit without saving?": "Tem certeza que deseja sair sem salvar?",
    "Save before closing?": "Salvar antes de fechar?",
    Copy: "Copiar",
    Cut: "Recortar",
    Paste: "Colar",
    "Deleting...": "Deletando...",
    "Copying...": "Copiando...",
    "Moving...": "Movendo...",
    Folders: "Pastas",
    "Search results": "Procurar Resultados",
    "Search results in": "Resultados da pesquisa em",
    "Search files and folders": "Pesquisar arquivos e pastas",
    "Add new file": "Adicionar novo arquivo",
    "Add new folder": "Adicionar nova pasta",
    "Upload file": "Enviar arquivo",
    folder: "pasta",
    file: "arquivo",
    archive: "arquivo",
    audio: "áudio",
    image: "imagem",
    video: "vídeo",
    code: "código",
    document: "documento",
    of: "de",
    used: "usado",
    "Open item location": "Abrir localização do item",
    "Are you sure you want to delete": "Tem certeza que deseja excluir",
    "these items:": "esses itens:",
    "this item:": "este item:",
    "Delete files": "Deletar arquivos",
    and: "e",
    "more file(s)": "mais arquivo(s)",
    "Close the editor": "Fechar o editor",
    "Close this file": "Fechar este arquivo",
    "Owner": "Proprietário",
    "Permissions": "Permissões",
    "Change Permissions": "Alterar permissões",
    "Set": "Definir",
    "Extract": "Extrair",
    "Extract directory": "Extrair diretório",
    "Extracting...": "Extraindo...",
    "Compress": "Compactar",
    "Compressing....": "Compactando....",
};
