var gr = {
    Save: "Αποθήκευση",
    "Save all": "Αποθήκευση όλων",
    Rename: "Μετονομασία",
    Open: "Άνοιγμα",
    Edit: "Επεξεργασία",
    Delete: "Διαγραφή",
    Folder: "Φάκελος",
    "Add New": "Προσθήκη Νέουw",
    Size: "Μέγεθος",
    Date: "Ημερομηνία",
    "back to parent folder": "επιστροφή στον γονικό φάκελο",
    Download: "Λήψη",
    Type: "Τύπος",
    Information: "Πληροφορία",
    Files: "Αρχεία",
    Table: "Πίνακας",
    Cards: "Κάρτες",
    Total: "Συνολικά",
    "Are you sure ?": "Είσαι σίγουρος;",
    Details: "Λεπτομέρειες",
    "Enter a new name": "Εισαγάγετε ένα νέο όνομα",
    Add: "Προσθήκη",
    "Select something": "Διαλέξτε κάτι",
    "Download file": "Λήψη αρχείου",
    Preview: "Προεπισκόπηση",
    Refresh: "Ανανέωση",
    "Are you sure you want to exit without saving?": "Είστε βέβαιοι ότι θέλετε να βγείτε χωρίς αποθήκευση;",
    "Save before closing?": "Αποθήκευση πριν από το κλείσιμο;",
    Copy: "Αντιγραφή",
    Cut: "Αποκοπή",
    Paste: "Επικόλληση",
    "Deleting...": "Διαφραφή...",
    "Copying...": "Αντιγραφή...",
    "Moving...": "Μεταφορά...",
    Folders: "Φάκελοι",
    "Search results": "Αποτελέσματα αναζήτησης",
    "Search results in": "Αποτελέσματα αναζήτησης στο",
    "Search files and folders": "Αναζήτηση αρχείων και φακέλων",
    "Add new file": "Προσθήκη νέου αρχείου",
    "Add new folder": "Προσθήκη νέου φακέλου",
    "Upload file": "Ανέβασμα αρχείου",
    folder: "φάκελος",
    file: "αρχείο",
    archive: "αρχειοθέτηση",
    audio: "ήχος",
    image: "εικόνα",
    video: "βίντεο",
    code: "κώδικας",
    document: "έγγραφο",
    of: "του",
    used: "χρησιμοποιημένο",
    "Open item location": "Ανοίξτε τη θέση του στοιχείου",
    "Are you sure you want to delete": "Είστε σίγουροι ότι θέλετε να διαγράψετε",
    "these items:": "αυτά τα αντικείμενα:",
    "this item:": "αυτό το αντικείμενο:",
    "Delete files": "Διαγραφή αρχείων",
    and: "και",
    "more file(s)": "περισσότερα αρχεία",
    "Close the editor": "Κλείστε το πρόγραμμα επεξεργασίας",
    "Close this file": "Κλείστε αυτό το αρχείο",
    "Owner": "Ιδιοκτήτης",
    "Permissions": "Άδειες",
    "Change Permissions": "Αλλαγή αδειών",
    "Set": "Ορισμός",
    "Extract": "Εξαγωγή",
    "Extract directory": "Εξαγωγή φακέλου",
    "Extracting...": "Γίνεται εξαγωγή...",
    "Compress": "Συμπίεση",
    "Compressing...": "Συμπίεση...",
};
