var ka_ge = {
    Save: "შენახვა",
    "Save all": "ყველაფრის შენახვა",
    Rename: "გადარქმევა",
    Open: "გახსნა",
    Edit: "რედაქტირება",
    Delete: "წაშლა",
    Folder: "საქაღალდე",
    "Add New": "ახლის დამატება",
    Size: "ზომა",
    Date: "თარიღი",
    "back to parent folder": "მთავარ საქაღალდეში დაბრუნება",
    Download: "გადმოწერა",
    Type: "ტიპი",
    Information: "ინფორმაცია",
    Files: "ფაილები",
    Table: "ცხრილი",
    Cards: "ბარათები",
    Total: "სულ",
    "Are you sure ?": "დარწმუნებლი ხართ?",
    Details: "დეტალები",
    "Enter a new name": "შეიყვანეთ ახალი სახელი",
    Add: "დამატება",
    "Select something": "მონიშნეთ რაიმე",
    "Download file": "ფაილის ჩამოტვირთვა",
    Preview: "გადახედვა",
    Refresh: "განახლება",
    "Are you sure you want to exit without saving?": "ნამდვილად გსურთ გამოსვლა შენახვის გარეშე?",
    "Save before closing?": "შევინახო სანამ დახურავთ?",
    Copy: "კოპირება",
    Cut: "ამოჭრა",
    Paste: "ჩასმა",
    "Deleting...": "მიმდინარეობს წაშლა...",
    "Copying...": "კოპირდება...",
    "Moving...": "გადაადგიდლება...",
    Folders: "საქაღალდეები",
    "Search results": "ძებნის შედეგები",
    "Search results in": "ძებნის შედეგები",
    "Search files and folders": "ფაილებისა და საქაღალდეების ძებნა",
    "Add new file": "ახალი ფაილის დამატება",
    "Add new folder": "ახალი საქაღალდეს დამატება",
    "Upload file": "ფაილის ატვირთვა",
    folder: "საქაღალდე",
    file: "ფაილი",
    archive: "არქივი",
    audio: "აუდიო",
    image: "სურათი",
    video: "ვიდეო",
    code: "კოდი",
    document: "დოკუმენტი",
    of: "",
    used: "გამოყენებული",
    "Open item location": "ელემენტის ადილმდებარეობის გახსნა",
    "Are you sure you want to delete": "დარწმუნებული ხართ, რომ წაშლა გსურთ?",
    "these items:": "ამ ელემენტებს:",
    "this item:": "este elemento:",
    "Delete files": "ფაილების წაშლა",
    and: "და",
    "more file(s)": "მეტი ფაილი(ები)",
    "Close the editor": "რედაქტორის დახურვა",
    "Close this file": "დახურე ეს ფაილი",
    "Owner": "მფლობელი",
    "Permissions": "უფლებები",
    "Change Permissions": "უფლებების შეცვლა",
    "Set": "დაყენება",
    "Extract": "გადმოტანა",
    "Extract directory": "Extraer directorio",
    "Extracting...": "გადმოდის...",
    "Compress": "შეკუმშვა",
    "Compressing...": "იკუმშება...",
};
