var en = {
    Save: "Salvează",
    "Save all": "Salează toate",
    Rename: "Redenumește",
    Open: "Deschide",
    Edit: "Editeză",
    Delete: "Șterge",
    Folder: "Folder",
    "Add New": "Adaugă un nou ",
    Size: "Mărime",
    Date: "Dată",
    "back to parent folder": "Înapoi la folder-ul părinte",
    Download: "Descarcă",
    Type: "Tip",
    Information: "Intormație",
    Files: "Fișiere",
    Table: "Tabel",
    Cards: "Carduri",
    Total: "Total",
    "Are you sure ?": "Ești sigur ?",
    Details: "Detalii",
    "Enter a new name": "Introdu un nume nou",
    Add: "Adaugă",
    "Select something": "Selectează ceva",
    "Download file": "Descarcă fișier",
    Preview: "Pre-vizualizează",
    Refresh: "Reîmprospăteză",
    "Are you sure you want to exit without saving?": "Ești sigur ca vrei să închizi fără să salvezi?",
    "Save before closing?": "Salvezi înainte să inchizi?",
    Copy: "Copiază",
    Cut: "Decupează",
    Paste: "Lipește",
    "Deleting...": "Ștergere...",
    "Copying...": "Copiere...",
    "Moving...": "Mutare...",
    Folders: "Foldere",
    "Search results": "Rezultatele căutării",
    "Search results in": "Rezultatele căutării în",
    "Search files and folders": "Caută fișiere și foldere",
    "Add new file": "Adaugă fișier nou",
    "Add new folder": "Adaugă folder nou",
    "Upload file": "Încarcă fișier",
    folder: "folder",
    file: "fișier",
    archive: "arhivă",
    audio: "audio",
    image: "imagine",
    video: "video",
    code: "cod sursa",
    document: "document",
    of: "din",
    used: "folosit",
    "Open item location": "Deschide locația articolului",
    "Are you sure you want to delete": "Ești sigur că vrei să ștergi",
    "these items:": "aceste articole:",
    "this item:": "acest articol:",
    "Delete files": "Șterge fișiere",
    and: "și",
    "more file(s)": "multe fișiere",
    "Close the editor": "Închide editorul",
    "Close this file": "Închide acest fișier",
    "Owner": "Proprietar",
    "Permissions": "Permisii",
    "Change Permissions": "Schimbă permisiile",
    "Set": "Setează",
    "Extract": "Extrage",
    "Extract directory": "Extract director",
    "Extracting...": "Extragere...",
    "Compress": "Compresează",
    "Compressing...": "Compresare...",
};