var ko = {
  Save: "저장",
  "Save all": "모두 저장",
  Rename: "이름 바꾸기",
  Open: "열기",
  Edit: "편집",
  Delete: "삭제",
  Folder: "폴더",
  "Add New": "새로 추가",
  Size: "크기",
  Date: "날짜",
  "back to parent folder": "상위 폴더로 가기",
  Download: "다운로드",
  Type: "타입",
  Information: "정보",
  Files: "파일",
  Table: "Table",
  Cards: "Cards",
  Total: "Total",
  "Are you sure ?": "정말인가요?",
  Details: "상세",
  "Enter a new name": "새로운 이름을 입력하세요",
  Add: "Add",
  "Select something": "항목 선택",
  "Download file": "파일 다운로드",
  Preview: "미리보기",
  Refresh: "새로고침",
  "Are you sure you want to exit without saving?":
    "정말 저장하지 않고 종료하시겠어요?",
  "Save before closing?": "닫기 전에 저장할까요?",
  Copy: "복사",
  Cut: "잘라내기",
  Paste: "붙여넣기",
  "Deleting...": "지우는 중...",
  "Copying...": "복사 중...",
  "Moving...": "옮기는 중...",
  Folders: "폴더",
  "Search results": "검색 결과",
  "Search results in": "검색 결과 :",
  "Search files and folders": "파일 및 폴더 검색",
  "Add new file": "새 파일 추가",
  "Add new folder": "새 폴더 추가",
  "Upload file": "파일 업로드",
  folder: "폴더",
  file: "파일",
  archive: "압축",
  audio: "오디오",
  image: "이미지",
  video: "비디오",
  code: "코드",
  document: "문서",
  of: "의",
  used: "사용",
  "Open item location": "항목 위치 열기",
  "Are you sure you want to delete": "정말 지우시겠어요?",
  "these items:": "이 항목들:",
  "this item:": "이 항목:",
  "Delete files": "파일 삭제",
  and: "and",
  "more file(s)": "more file(s)",
  "Close the editor": "편집기 닫기",
  "Close this file": "이 파일 닫기",
  Owner: "소유자",
  Permissions: "권한",
  "Change Permissions": "권한 변경하기",
  Set: "설정",
  Extract: "압축 풀기",
  "Extract directory": "디렉터리에 풀기",
  "Extracting...": "압축 해제 중...",
  Compress: "압축하기",
  "Compressing...": "압축 중...",
};
