var bs = {
    Save: "Sačuvaj",
    "Save all": "Sačuvaj sve",
    Rename: "Preimenuj",
    Open: "Otvori",
    Edit: "Uredi",
    Delete: "Obriši",
    Folder: "Folder",
    "Add New": "Dodaj Novi",
    Size: "Veličina",
    Date: "Datum",
    "back to parent folder": "Nazad na roditeljski folder",
    Download: "Preuzmi",
    Type: "Tip",
    Information: "Informacije",
    Files: "Datoteke",
    Table: "Tabela",
    Cards: "Kartice",
    Total: "Ukupno",
    "Are you sure ?": "Jeste li sigurni?",
    Details: "Detalji",
    "Enter a new name": "Unesite novo ime",
    Add: "Dodaj",
    "Select something": "Izaberite nešto",
    "Download file": "Preuzmi datoteku",
    Preview: "Pregled",
    Refresh: "Osveži",
    "Are you sure you want to exit without saving?": "Jeste li sigurni da želite izaći bez čuvanja izmena?",
    "Save before closing?": "Sačuvaj pre zatvaranja?",
    Copy: "Kopiraj",
    Cut: "Iseci",
    Paste: "Zalepi",
    "Deleting...": "Brisanje...",
    "Copying...": "Kopiranje...",
    "Moving...": "Premeštanje...",
    Folders: "Folderi",
    "Search results": "Rezultati pretrage",
    "Search results in": "Rezultati pretrage u",
    "Search files and folders": "Pretraži datoteke i foldere",
    "Add new file": "Dodaj novu datoteku",
    "Add new folder": "Dodaj novi folder",
    "Upload file": "Otpremi datoteku",
    folder: "folder",
    file: "datoteka",
    archive: "arhiva",
    audio: "audio",
    image: "slika",
    video: "video",
    code: "kod",
    document: "dokument",
    of: "od",
    used: "iskorišteno",
    "Open item location": "Otvori lokaciju stavke",
    "Are you sure you want to delete": "Jeste li sigurni da želite izbrisati",
    "these items:": "ove stavke:",
    "this item:": "ovu stavku:",
    "Delete files": "Obriši datoteke",
    and: "i",
    "more file(s)": "više datoteka",
    "Close the editor": "Zatvori editor",
    "Close this file": "Zatvori ovu datoteku",
    "Owner": "Vlasnik",
    "Permissions": "Dozvole",
    "Change Permissions": "Promeni dozvole",
    "Set": "Postavi",
    "Extract": "Raspakuj",
    "Extract directory": "Raspakuj direktorijum",
    "Extracting...": "Raspakivanje...",
    "Compress": "Kompresuj",
    "Compressing...": "Kompresovanje...",
};
