var pl = {
    Save: "Zapisz",
    "Save all": "Zapisz wszystko",
    Rename: "Zmień nazwę",
    Open: "Otwórz",
    Edit: "Edytuj",
    Delete: "Usuń",
    Folder: "Folder",
    "Add New": "Dodaj nowy",
    Size: "Rozmiar",
    Date: "Data",
    "back to parent folder": "powrót do folderu nadrzędnego",
    Download: "Pobierz",
    Type: "Typ",
    Information: "Informacja",
    Files: "Pliki",
    Table: "Tabela",
    Cards: "Karty",
    Total: "Razem",
    "Are you sure ?": "Czy jesteś pewny/a ?",
    Details: "Szczegóły",
    "Enter a new name": "Wprowadź nową nazwę",
    Add: "Dodaj",
    "Select something": "Wybierz coś",
    "Download file": "Pobierz plik",
    Preview: "Podgląd",
    Refresh: "Odśwież",
    "Are you sure you want to exit without saving?": "Czy jesteś pewny/a, że chcesz porzucić okno bez zapisywania?",
    "Save before closing?": "Zapisz przed zamknięciem?",
    Copy: "Kopiuj",
    Cut: "Wytnij",
    Paste: "Wklej",
    "Deleting...": "Usuwanie...",
    "Copying...": "Kopiowanie...",
    "Moving...": "Przenoszenie...",
    Folders: "Foldery",
    "Search results": "Wyniki wyszukiwania",
    "Search results in": "Wyniki wyszukiwania w",
    "Search files and folders": "Szukaj plików i folderów",
    "Add new file": "Dodaj nowy plik",
    "Add new folder": "Dodaj nowy folder",
    "Upload file": "Wgraj plik",
    folder: "folder",
    file: "plik",
    archive: "archiwum",
    audio: "audio",
    image: "obraz",
    video: "video",
    code: "kod",
    document: "dokument",
    of: "of",
    used: "użyty",
    "Open item location": "Otwórz lokalizację elementu",
    "Are you sure you want to delete": "Czy jesteś pewny/a, że chcesz to usunąć",
    "these items:": "te elementy:",
    "this item:": "ten element:",
    "Delete files": "Usuń pliki",
    and: "oraz",
    "more file(s)": "więcej plik(ów)",
    "Close the editor": "Zamknij edytor",
    "Close this file": "Zamknij ten plik",
    "Owner": "Właściciel",
    "Permissions": "Uprawnienia",
    "Change Permissions": "Zmień Uprawnienia",
    "Set": "Zbiór",
    "Extract": "Wyodrębnij",
    "Extract directory": "Wyodrębnij katalog",
    "Extracting...": "Wyodrębnianie...",
    "Compress": "Kompresuj",
    "Compressing...": "Kompresja...",
};
